name: "Build and push to cachix"
on:
  pull_request:
jobs:
  build_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: horriblename
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      # I really shouldn't hard code build system here...
      - run: "nix build --no-link .#ciHelpers.x86_64-linux.testTargets.aarch64-linux"
